export const PodcastActionTypes = {
  RECEIVE_PODCASTS: "RECEIVE_PODCASTS",
  RECEIVE_PODCAST_YOUTUBE_CHANNEL_PROFILE:
    "RECEIVE_PODCAST_YOUTUBE_CHANNEL_PROFILE",
  SEARCH_PODCASTS: "SEARCH_PODCASTS",
}
